# Configuración de Kafka para el productor
spring:
  kafka:
    producer:
      acks: -1 # Número de replicas a esperar para confirmar la escritura en el broker (-1 para todas)
      bootstrap-servers: localhost:29092 # Direcciones de los servidores Kafka (broker)
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # Serializador de claves
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # Serializador de valores (usando JsonSerializer de Spring Kafka)
